# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from tensorflow.keras.utils import to_categorical

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    Path("applicants_data.csv")
)
# Review the DataFrame
applicant_data_df.head(10)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
5,10556855,MINORITY ORGAN & TISSUE TRANSPLANT & EDUCATION...,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
6,10558440,FRIENDS OF ARTS COUNCIL OF GREATER DENHAM SPRI...,T3,Independent,C1000,Preservation,Trust,1,100000-499999,N,31452,1
7,10566033,ISRAEL EMERGENCY ALLIANCE,T3,Independent,C2000,Preservation,Trust,1,10M-50M,N,7508025,1
8,10570430,ARAMCO BRATS INC,T7,Independent,C1000,ProductDev,Trust,1,1-9999,N,94389,1
9,10571689,INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0

In [3]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN', 'NAME'])


# Review the DataFrame
applicant_data_df.head(10)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
5,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
6,T3,Independent,C1000,Preservation,Trust,1,100000-499999,N,31452,1
7,T3,Independent,C2000,Preservation,Trust,1,10M-50M,N,7508025,1
8,T7,Independent,C1000,ProductDev,Trust,1,1-9999,N,94389,1
9,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [7]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

/Users/russellgould/miniforge3/envs/tensorflow/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [8]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
     columns = enc.get_feature_names_out(categorical_variables)
)
# Review the DataFrame
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [9]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numerical_variables_df = applicant_data_df.drop(columns = categorical_variables)
numerical_variables_df = numerical_variables_df.drop(columns = ['IS_SUCCESSFUL'])

applicant_data_encoded_df = pd.concat(
    [
        numerical_variables_df,
        encoded_df
    ],
    axis=1
)

# Reveiw the DataFrame
applicant_data_encoded_df.head(100)

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
96,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
97,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
98,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
99,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [10]:
# Define the target set y using the IS_SUCCESSFUL column
y = applicant_data_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [11]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = applicant_data_encoded_df

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [12]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [13]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [14]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [15]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [16]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + 1) // 2 

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [17]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [18]:
# Create the Sequential model instance
nn = Sequential()

2023-12-17 13:41:32.078194: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2023-12-17 13:41:32.078215: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2023-12-17 13:41:32.078220: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2023-12-17 13:41:32.078255: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-12-17 13:41:32.078276: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [19]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [20]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [21]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [22]:
# Display the Sequential model summary
# YOUR CODE HERE
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8527 (33.31 KB)
Trainable params: 8527 (33.31 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [23]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
 11/804 [..............................] - ETA: 3s - loss: 0.7815 - accuracy: 0.6420

2023-12-17 13:41:32.387302: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

804/804 [==============================] - 4s 4ms/step - loss: 0.6216 - accuracy: 0.7128
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5966 - accuracy: 0.7158
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6117 - accuracy: 0.7061
Epoch 4/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6350 - accuracy: 0.6960
Epoch 5/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6632 - accuracy: 0.6857
Epoch 6/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6736 - accuracy: 0.6799
Epoch 7/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7037 - accuracy: 0.6714
Epoch 8/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7382 - accuracy: 0.6633
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7301 - accuracy: 0.6671
Epoch 10/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7826 - accuracy: 0.6537
Epoch 11/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8085 - accuracy: 0.6564
Epoch 12/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7889 - accuracy: 0.6521
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8556 - accuracy: 0.6443
Epoch 14/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8722 - accuracy: 0.6452
Epoch 15/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8585 - accuracy: 0.6443
Epoch 16/50
804/804 [==============================] - 3s 4ms/step - loss: 0.9804 - accuracy: 0.6307
Epoch 17/50
804/804 [==============================] - 3s 4ms/step - loss: 1.0653 - accuracy: 0.6330
Epoch 18/50
804/804 [==============================] - 3s 4ms/step - loss: 1.0255 - accuracy: 0.6370
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 1.0105 - accuracy: 0.6365
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 1.0537 - accuracy: 0.6297
Epoch 21/50
804/804 [==============================] - 3s 4ms/step - loss: 1.3287 - accuracy: 0.6198
Epoch 22/50
804/804 [==============================] - 3s 4ms/step - loss: 1.1661 - accuracy: 0.6244
Epoch 23/50
804/804 [==============================] - 3s 4ms/step - loss: 1.1222 - accuracy: 0.6288
Epoch 24/50
804/804 [==============================] - 3s 4ms/step - loss: 1.2704 - accuracy: 0.6235
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 1.2491 - accuracy: 0.6248
Epoch 26/50
804/804 [==============================] - 3s 4ms/step - loss: 1.2780 - accuracy: 0.6246
Epoch 27/50
804/804 [==============================] - 3s 4ms/step - loss: 1.3730 - accuracy: 0.6232
Epoch 28/50
804/804 [==============================] - 3s 4ms/step - loss: 1.3393 - accuracy: 0.6178
Epoch 29/50
804/804 [==============================] - 3s 4ms/step - loss: 1.5189 - accuracy: 0.6212
Epoch 30/50
804/804 [==============================] - 3s 4ms/step - loss: 1.5134 - accuracy: 0.6230
Epoch 31/50
804/804 [==============================] - 3s 4ms/step - loss: 1.5076 - accuracy: 0.6191
Epoch 32/50
804/804 [==============================] - 3s 4ms/step - loss: 1.7355 - accuracy: 0.6123
Epoch 33/50
804/804 [==============================] - 3s 4ms/step - loss: 1.6565 - accuracy: 0.6174
Epoch 34/50
804/804 [==============================] - 3s 4ms/step - loss: 1.7091 - accuracy: 0.6151
Epoch 35/50
804/804 [==============================] - 3s 4ms/step - loss: 1.7571 - accuracy: 0.6128
Epoch 36/50
804/804 [==============================] - 3s 4ms/step - loss: 1.7556 - accuracy: 0.6163
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 1.8745 - accuracy: 0.6194
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 2.1264 - accuracy: 0.6075
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 2.2055 - accuracy: 0.6146
Epoch 40/50
804/804 [==============================] - 61s 76ms/step - loss: 2.2616 - accuracy: 0.6113
Epoch 41/50
804/804 [==============================] - 3s 4ms/step - loss: 2.2602 - accuracy: 0.6145
Epoch 42/50
804/804 [==============================] - 25s 31ms/step - loss: 2.6418 - accuracy: 0.6103
Epoch 43/50
804/804 [==============================] - 3s 4ms/step - loss: 2.2916 - accuracy: 0.6120
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 2.4133 - accuracy: 0.6116
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 2.6336 - accuracy: 0.6124
Epoch 46/50
804/804 [==============================] - 3s 4ms/step - loss: 3.0512 - accuracy: 0.6054
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 2.8793 - accuracy: 0.6092
Epoch 48/50
804/804 [==============================] - 3s 4ms/step - loss: 3.1882 - accuracy: 0.6100
Epoch 49/50
804/804 [==============================] - 3s 4ms/step - loss: 2.6477 - accuracy: 0.6146
Epoch 50/50
804/804 [==============================] - 3s 4ms/step - loss: 3.1342 - accuracy: 0.6093

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [25]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

2023-12-17 13:45:40.594487: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

268/268 - 1s - loss: 3.0553 - accuracy: 0.7139 - 705ms/epoch - 3ms/step
Loss: 3.0553436279296875, Accuracy: 0.7139358520507812

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [26]:
# Save model in JSON format
nn_json = nn.to_json()

# Set the model's file path
file_path = Path("AlphabetSoup.json")

# Write the model to the the file 
with open(file_path, "w") as json_file:
    json_file.write(nn_json)

# Define a relative path to save the model weights
# The model weights should be saved with a .h5 file extension
file_path = "AlphabetSoup.h5"

# Save the weights to the file path
nn.save_weights(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [27]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [28]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [29]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features + 1) // 6 

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

19

In [30]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [31]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 19)                2223

 dense_4 (Dense)             (None, 1)                 20

=================================================================
Total params: 2243 (8.76 KB)
Trainable params: 2243 (8.76 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [32]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [33]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
 13/804 [..............................] - ETA: 3s - loss: 0.8230 - accuracy: 0.4832

2023-12-17 13:45:41.463256: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

804/804 [==============================] - 3s 4ms/step - loss: 0.6576 - accuracy: 0.7020
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5991 - accuracy: 0.7208
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5860 - accuracy: 0.7200
Epoch 4/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5802 - accuracy: 0.7205
Epoch 5/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5778 - accuracy: 0.7204
Epoch 6/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5771 - accuracy: 0.7218
Epoch 7/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5770 - accuracy: 0.7193
Epoch 8/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5774 - accuracy: 0.7215
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5776 - accuracy: 0.7201
Epoch 10/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5774 - accuracy: 0.7195
Epoch 11/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5777 - accuracy: 0.7193
Epoch 12/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5780 - accuracy: 0.7196
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5778 - accuracy: 0.7197
Epoch 14/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5785 - accuracy: 0.7187
Epoch 15/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5782 - accuracy: 0.7203
Epoch 16/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5788 - accuracy: 0.7167
Epoch 17/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5785 - accuracy: 0.7195
Epoch 18/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5783 - accuracy: 0.7193
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5793 - accuracy: 0.7182
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5780 - accuracy: 0.7197
Epoch 21/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5791 - accuracy: 0.7204
Epoch 22/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5783 - accuracy: 0.7182
Epoch 23/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5795 - accuracy: 0.7177
Epoch 24/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5801 - accuracy: 0.7199
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5797 - accuracy: 0.7191
Epoch 26/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5789 - accuracy: 0.7195
Epoch 27/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5787 - accuracy: 0.7192
Epoch 28/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5802 - accuracy: 0.7186
Epoch 29/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5795 - accuracy: 0.7182
Epoch 30/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5814 - accuracy: 0.7200
Epoch 31/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5805 - accuracy: 0.7191
Epoch 32/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5799 - accuracy: 0.7215
Epoch 33/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5809 - accuracy: 0.7182
Epoch 34/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5823 - accuracy: 0.7168
Epoch 35/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5795 - accuracy: 0.7201
Epoch 36/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5804 - accuracy: 0.7188
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5822 - accuracy: 0.7178
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5822 - accuracy: 0.7172
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5813 - accuracy: 0.7186
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5828 - accuracy: 0.7175
Epoch 41/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5810 - accuracy: 0.7193
Epoch 42/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5855 - accuracy: 0.7170
Epoch 43/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5820 - accuracy: 0.7179
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5825 - accuracy: 0.7168
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5826 - accuracy: 0.7169
Epoch 46/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5836 - accuracy: 0.7176
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5825 - accuracy: 0.7184
Epoch 48/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5860 - accuracy: 0.7156
Epoch 49/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5850 - accuracy: 0.7176
Epoch 50/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5824 - accuracy: 0.7171

#### Alternative Model 2

In [34]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [35]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [36]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features + 1) // 4 

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

29

In [37]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2 = (hidden_nodes_layer1_A2 + 1) // 4

# Review the number hidden nodes in the second layer
hidden_nodes_layer2_A2

7

In [38]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [39]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))

# Add the second hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer2_A2, activation="relu"))

# Output layer
nn_A2.add(Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 29)                3393

 dense_6 (Dense)             (None, 7)                 210

 dense_7 (Dense)             (None, 1)                 8

=================================================================
Total params: 3611 (14.11 KB)
Trainable params: 3611 (14.11 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [40]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [41]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
 10/804 [..............................] - ETA: 4s - loss: 0.7210 - accuracy: 0.6438

2023-12-17 13:48:17.561574: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

804/804 [==============================] - 4s 4ms/step - loss: 0.6364 - accuracy: 0.7069
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5930 - accuracy: 0.7201
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5881 - accuracy: 0.7203
Epoch 4/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5905 - accuracy: 0.7173
Epoch 5/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5957 - accuracy: 0.7152
Epoch 6/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6056 - accuracy: 0.7105
Epoch 7/50
804/804 [==============================] - 4s 4ms/step - loss: 0.6056 - accuracy: 0.7137
Epoch 8/50
804/804 [==============================] - 4s 4ms/step - loss: 0.6124 - accuracy: 0.7074
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6199 - accuracy: 0.7085
Epoch 10/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6233 - accuracy: 0.7034
Epoch 11/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6258 - accuracy: 0.6996
Epoch 12/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6313 - accuracy: 0.6968
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6353 - accuracy: 0.6941
Epoch 14/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6333 - accuracy: 0.6949
Epoch 15/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6363 - accuracy: 0.6959
Epoch 16/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6423 - accuracy: 0.6918
Epoch 17/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6504 - accuracy: 0.6858
Epoch 18/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6524 - accuracy: 0.6824
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6684 - accuracy: 0.6787
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6593 - accuracy: 0.6847
Epoch 21/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6566 - accuracy: 0.6858
Epoch 22/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6858 - accuracy: 0.6719
Epoch 23/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6932 - accuracy: 0.6726
Epoch 24/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6907 - accuracy: 0.6691
Epoch 25/50
804/804 [==============================] - 4s 4ms/step - loss: 0.7137 - accuracy: 0.6642
Epoch 26/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7003 - accuracy: 0.6670
Epoch 27/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7226 - accuracy: 0.6609
Epoch 28/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7278 - accuracy: 0.6653
Epoch 29/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7244 - accuracy: 0.6606
Epoch 30/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7103 - accuracy: 0.6673
Epoch 31/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7325 - accuracy: 0.6575
Epoch 32/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7736 - accuracy: 0.6494
Epoch 33/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7535 - accuracy: 0.6597
Epoch 34/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7779 - accuracy: 0.6606
Epoch 35/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7828 - accuracy: 0.6482
Epoch 36/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8314 - accuracy: 0.6443
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7769 - accuracy: 0.6503
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7871 - accuracy: 0.6525
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7865 - accuracy: 0.6534
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8490 - accuracy: 0.6412
Epoch 41/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8031 - accuracy: 0.6525
Epoch 42/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8762 - accuracy: 0.6430
Epoch 43/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8064 - accuracy: 0.6476
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8827 - accuracy: 0.6371
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 0.9113 - accuracy: 0.6399
Epoch 46/50
804/804 [==============================] - 3s 4ms/step - loss: 0.9417 - accuracy: 0.6390
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8406 - accuracy: 0.6427
Epoch 48/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8530 - accuracy: 0.6439
Epoch 49/50
804/804 [==============================] - 3s 4ms/step - loss: 0.9831 - accuracy: 0.6386
Epoch 50/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8832 - accuracy: 0.6427

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [42]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 1s - loss: 3.0553 - accuracy: 0.7139 - 607ms/epoch - 2ms/step
Loss: 3.0553436279296875, Accuracy: 0.7139358520507812

In [43]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results

2023-12-17 13:51:09.869885: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

268/268 - 1s - loss: 0.5891 - accuracy: 0.7217 - 679ms/epoch - 3ms/step
Loss: 0.5890871286392212, Accuracy: 0.7217492461204529

In [44]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results

2023-12-17 13:51:10.572455: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

268/268 - 1s - loss: 0.7583 - accuracy: 0.6827 - 715ms/epoch - 3ms/step
Loss: 0.7582945823669434, Accuracy: 0.68268221616745

### Step 3: Save each of your alternative models as an HDF5 file.

In [45]:
# Save model in JSON format
nn_A1_json = nn_A1.to_json()

# Set the model's file path
file_path = Path("AlphabetSoup_A1.json")

# Write the model to the the file 
with open(file_path, "w") as json_file:
    json_file.write(nn_A1_json)

# Define a relative path to save the model weights
# The model weights should be saved with a .h5 file extension
file_path = "AlphabetSoup_A1.h5"

# Save the weights to the file path
nn_A1.save_weights(file_path)

In [46]:
# Save model in JSON format
nn_A2_json = nn_A2.to_json()

# Set the model's file path
file_path = Path("AlphabetSoup_A2.json")

# Write the model to the the file 
with open(file_path, "w") as json_file:
    json_file.write(nn_A2_json)

# Define a relative path to save the model weights
# The model weights should be saved with a .h5 file extension
file_path = "AlphabetSoup_A2.h5"

# Save the weights to the file path
nn_A2.save_weights(file_path)